- name: variables to print
  hosts: web
  vars:
   COURSE: "Devops with Aws"
   TIME: "120 hours"
   TRAINER: "Vijay Chowdary"
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi I am leaening {{COURSE}}, Duration is {{TIME}}, and the trainer is {{TRAINER}}" 

  - name: print the info again
    vars:
     COURSE: "Ansible"
    ansible.builtin.debug:
     msg: "Hi I am leaening {{COURSE}}, Duration is {{TIME}}, and the trainer is {{TRAINER}}"

  - name: print the info again and again
    ansible.builtin.debug:
     msg: "Hi I am leaening {{COURSE}}, Duration is {{TIME}}, and the trainer is {{TRAINER}}"